### ISSUE TITLE
ZyROS_MessageType_Instantiations

### ISSUE THREAD

**Issue by robotsorcerer** [faichele/SofaROSConnector#1]
Hi @faichele, I was wondering what version of SOFA you compiled the ZyROSConnector with.

I am using v19.06 currently and I can't get the header files in ZyROSConnector to build:

```
CMake Error at applications/plugins/SofaROSConnector/ZyROSConnectionManager/CMakeLists.txt:67 (add_library):
  Cannot find source file:

    /home/lex/sofa/build/applications/plugins/ZyROSConnector/ZyROSConnectionManager/ZyROS_MessageType_Instantiations.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
```

**Comment by robotsorcerer** [comment]
I THINK THIS MIGHT HAVE BEEN A RESULT OF MY MULTI-TASKING MANY PROJECTS DURING LAST WEEK.

I just found a little while ago that this was mostly due to me turning off PLUGIN_SOFAROSCONNECTOR during cmake build. Sorry for the trouble!

**Comment by ljjTYJR** [comment]
hello, I meet with the same problem. I did not find PLUGIN_SOFAROSCONNECTOR. 
how you solve the problem? @lakehanne
